FROM python:3.12.4

ARG PYINSTALLER_VERSION=6.9.0
ENV DEBIAN_FRONTEND=noninteractive

VOLUME /app/

COPY dockerfiles/entrypoint.sh /entrypoint.sh

RUN apt update \
    && apt install -y \
    binutils \
    gcc \
    zlib1g-dev \
    && apt clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /var/cache/* \
    && pip3 install \
    pyinstaller==$PYINSTALLER_VERSION \
    && pip3 cache purge \
    && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]